// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/*
 * ═════════════════════════════════════════════════════════════════════════════
 * BeTrueCore — NINNullifierRegistry.sol
 * On-chain registry for ZK identity proofs
 *
 * Author:  Farman Guliyev (Safarnur)
 * ORCID:   0009-0004-4841-594X
 * GitHub:  github.com/Dede-Qorqud/BeTrueCore
 * Version: 0.1 — MVP Contract
 * ═════════════════════════════════════════════════════════════════════════════
 *
 * PURPOSE
 * ───────
 * This contract is the on-chain counterpart to NINIdentityProof.circom.
 * It stores:
 *   1. The Merkle root of the registered voter tree
 *   2. Which nullifiers have been used (per session)
 *
 * And verifies:
 *   - A valid Groth16 ZK proof (via the generated Verifier.sol)
 *   - That the nullifier has not been used before in this session
 *
 * CRITICAL PROPERTY: The NIN code itself NEVER appears anywhere in this
 * contract, in any transaction, or in any event. The contract only ever
 * sees: merkle_root, session_id, nullifier, and the Groth16 proof bytes.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * INTEGRATION WITH BeTrueCore ARCHITECTURE:
 *
 *   L0 (Identity)  — NIN + Web3Auth MPC → commitment (client-side)
 *   L1 (Proofs)    ← THIS CONTRACT — verifies ZK proof, stores nullifier
 *   L2 (Execution) — Poll.sol calls verifyAndRegister() before counting vote
 *   L3 (Lock)      — Lit Protocol time-lock (Phase 2)
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * GROTH16 VERIFIER:
 *
 *   The IGroth16Verifier interface below must be implemented by the Verifier.sol
 *   contract generated by snarkjs after the trusted setup:
 *
 *     $ snarkjs groth16 setup NINIdentityProof.r1cs pot20_final.ptau proof_0000.zkey
 *     $ snarkjs zkey contribute proof_0000.zkey proof_0001.zkey --name="BeTrueCore"
 *     $ snarkjs zkey export solidityverifier proof_0001.zkey Verifier.sol
 *
 *   Deploy Verifier.sol first, then pass its address to this constructor.
 *
 * ═════════════════════════════════════════════════════════════════════════════
 */

/// @title IGroth16Verifier
/// @notice Interface for the snarkjs-generated Groth16 verifier contract
/// @dev Generated by: snarkjs zkey export solidityverifier
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof
    /// @param a      Proof element A  (G1 point)
    /// @param b      Proof element B  (G2 point)
    /// @param c      Proof element C  (G1 point)
    /// @param input  Public inputs in the order declared in the circuit:
    ///               [0] = merkle_root
    ///               [1] = external_nullifier (session_id)
    ///               [2] = nullifier (output signal — treated as public input here)
    /// @return true if proof is valid
    function verifyProof(
        uint256[2]    calldata a,
        uint256[2][2] calldata b,
        uint256[2]    calldata c,
        uint256[3]    calldata input
    ) external view returns (bool);
}


/// @title NINNullifierRegistry
/// @notice On-chain ZK identity proof registry for BeTrueCore
contract NINNullifierRegistry {

    // ══════════════════════════════════════════════════════════════════════
    // STATE
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Current Merkle root of the registered voter tree
    /// @dev Updated when new citizens are registered
    ///      In production: updated via governance, not admin
    bytes32 public merkleRoot;

    /// @notice Tracks which nullifiers have been used, per session
    /// @dev nullifiers[session_id][nullifier] = true if already submitted
    ///      Key insight: same nullifier in a new session is allowed
    ///      (different external_nullifier → different circuit output)
    mapping(uint256 => mapping(bytes32 => bool)) public nullifiers;

    /// @notice Groth16 verifier contract (generated by snarkjs)
    /// @dev Immutable — changing the verifier requires redeployment
    IGroth16Verifier public immutable verifier;

    /// @notice Admin address
    /// @dev For MVP: single admin. For production: replace with governance
    address public admin;

    // ══════════════════════════════════════════════════════════════════════
    // EVENTS
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Emitted when the voter Merkle root is updated
    event MerkleRootUpdated(
        bytes32 indexed oldRoot,
        bytes32 indexed newRoot,
        uint256 timestamp
    );

    /// @notice Emitted when a valid ZK identity proof is accepted
    /// @dev This is the only on-chain record of participation.
    ///      It contains NO information about who the participant is.
    event IdentityVerified(
        uint256 indexed sessionId,
        bytes32 indexed nullifier,
        uint256 timestamp
    );

    // ══════════════════════════════════════════════════════════════════════
    // ERRORS
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Thrown when a citizen tries to enter the same session twice
    /// @dev Sybil prevention: one citizen = one session entry ticket.
    ///      Multiple choice changes within the session are allowed via
    ///      Poll.sol key rotation (MACI anti-coercion pattern).
    ///      Only the final choice at time lock is counted.
    error NullifierAlreadyUsed(uint256 sessionId, bytes32 nullifier);

    /// @notice Thrown when the Groth16 proof fails verification
    error InvalidZKProof();

    /// @notice Thrown when caller is not the admin
    error OnlyAdmin();

    // ══════════════════════════════════════════════════════════════════════
    // CONSTRUCTOR
    // ══════════════════════════════════════════════════════════════════════

    /// @param _verifier     Address of the snarkjs-generated Verifier.sol
    /// @param _initialRoot  Initial Merkle root (empty tree or first batch)
    constructor(address _verifier, bytes32 _initialRoot) {
        require(_verifier != address(0), "Verifier: zero address");
        verifier    = IGroth16Verifier(_verifier);
        merkleRoot  = _initialRoot;
        admin       = msg.sender;
    }

    // ══════════════════════════════════════════════════════════════════════
    // ADMIN
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Update the registered voter Merkle root
    /// @dev Called when a new citizen registers — their commitment
    ///      is added as a leaf and the root is updated off-chain,
    ///      then committed here.
    ///      For production: replace with multi-sig or Thermostat governance
    /// @param _newRoot  New Merkle root after adding the latest registrations
    function updateMerkleRoot(bytes32 _newRoot) external {
        if (msg.sender != admin) revert OnlyAdmin();
        require(_newRoot != bytes32(0), "Root: cannot be zero");

        emit MerkleRootUpdated(merkleRoot, _newRoot, block.timestamp);
        merkleRoot = _newRoot;
    }

    // ══════════════════════════════════════════════════════════════════════
    // CORE — VERIFY AND REGISTER
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Verify a ZK identity proof and register the nullifier
    ///
    /// @dev Called by Poll.sol (L2) before accepting a vote.
    ///      Enforces two guarantees in a single atomic call:
    ///        1. The proof is cryptographically valid
    ///        2. This nullifier has not been used in this session
    ///
    ///      What the contract learns: session_id, nullifier, block timestamp.
    ///      What the contract does NOT learn: who the voter is, their NIN,
    ///      their commitment leaf, or their vote choice.
    ///
    /// @param sessionId    Active session ID (= external_nullifier in circuit)
    /// @param nullifier    Nullifier from the ZK proof output
    /// @param zkProof_a    Groth16 proof component A
    /// @param zkProof_b    Groth16 proof component B
    /// @param zkProof_c    Groth16 proof component C
    /// @return             true — always, or reverts
    function verifyAndRegister(
        uint256           sessionId,
        bytes32           nullifier,
        uint256[2]    calldata zkProof_a,
        uint256[2][2] calldata zkProof_b,
        uint256[2]    calldata zkProof_c
    ) external returns (bool) {

        // ── Guard 1: Nullifier must be fresh for this session ─────────────
        // Prevents Sybil attack: if the same citizen tries to enter the
        // same session under two different identities, the second attempt
        // produces the same nullifier (Poseidon(secret, session_id) is
        // deterministic) → rejected here.
        //
        // IMPORTANT: This does NOT prevent choice changes within the session.
        // A citizen who entered with this nullifier can still rotate their
        // choice via Poll.sol as many times as needed until the time lock.
        // That is the anti-coercion mechanism — not a bug, a feature.
        if (nullifiers[sessionId][nullifier]) {
            revert NullifierAlreadyUsed(sessionId, nullifier);
        }

        // ── Guard 2: ZK proof must be valid ──────────────────────────────
        // Public inputs passed to the verifier must match the circuit:
        //   [0] = merkle_root        (current on-chain root)
        //   [1] = external_nullifier (= sessionId)
        //   [2] = nullifier          (circuit output, treated as public input)
        uint256[3] memory publicInputs = [
            uint256(merkleRoot),
            sessionId,
            uint256(nullifier)
        ];

        bool valid = verifier.verifyProof(
            zkProof_a,
            zkProof_b,
            zkProof_c,
            publicInputs
        );

        if (!valid) revert InvalidZKProof();

        // ── Register nullifier (prevents future Sybil entry) ─────────────
        // Marks this citizen as "entered the session".
        // Does not lock their choice — Poll.sol key rotation remains open
        // until the Lit Protocol time lock closes the session.
        nullifiers[sessionId][nullifier] = true;

        emit IdentityVerified(sessionId, nullifier, block.timestamp);

        return true;
    }

    // ══════════════════════════════════════════════════════════════════════
    // VIEW
    // ══════════════════════════════════════════════════════════════════════

    /// @notice Check if a nullifier has already been used in a session
    /// @dev Used by Poll.sol for pre-flight checks before calling verifyAndRegister
    function isNullifierUsed(
        uint256 sessionId,
        bytes32 nullifier
    ) external view returns (bool) {
        return nullifiers[sessionId][nullifier];
    }

    /// @notice Returns the current Merkle root
    function currentMerkleRoot() external view returns (bytes32) {
        return merkleRoot;
    }
}
